<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<ProjectExperiment>
		<window>
			<RelativeDocumentPlacement type="key">1:m 0 Instrumentation|aea2dd7e-6365-485c-9e5a-ac799b926a4a/1:m 1 Instrumentation|029c9c1d-8b44-4284-9961-2a62c94a3177/2:</RelativeDocumentPlacement>
		</window>
		<viewflags>
			<Name type="key">Test_Digital_Out.CDE</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">Test_Digital_Out</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment Layouts</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">Test_Digital_Out.cdc</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">DIGITAL_ANALOG_OUT.lay</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">ANALOG INPUT.lay</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Hardware Configurations</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">5ea05e8a-5c46-4dec-96a5-06331419a5ec</Name>
						<ViewFlags type="key">65</ViewFlags>
						<item>
							<Name type="key">module_test_5v.sdf</Name>
							<ViewFlags type="key">1</ViewFlags>
							<item>
								<Name type="key">Data Sets</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
						</item>
					</item>
				</item>
				<item>
					<Name type="key">Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Measurement Data</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Reports</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Python Scripts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Signal Generators</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">BusNavigator</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">XIL API EESPorts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">AutomationCustomData.json</Name>
				<ViewFlags type="key">1</ViewFlags>
			</item>
			<item>
				<Name type="key">Events</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment.events</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
		</viewflags>
	</ProjectExperiment>
	<Interpreter Version="2">
		<Project>
			<ScriptCount type="key">0</ScriptCount>
		</Project>
		<Experiment>
			<ScriptCount type="key">0</ScriptCount>
		</Experiment>
	</Interpreter>
	<SignalEditor>
		<OpenSignalDescriptionSets Version="1"/>
		<OpenSignalGenerators Version="1"/>
		<Documents Version="1"/>
	</SignalEditor>
	<BusNavigator>
		<Documents Version="1"/>
	</BusNavigator>
	<Instrumentation>
		<Layouts Version="3">
			<Layout1>
				<Data type="key">DIGITAL_ANALOG_OUT.lay|1|aea2dd7e-6365-485c-9e5a-ac799b926a4a/1|1:sm:mm 26 26 777 406 -1 -1:</Data>
			</Layout1>
			<Layout2>
				<Data type="key">ANALOG INPUT.lay|1|029c9c1d-8b44-4284-9961-2a62c94a3177/2|1:sm:mm 52 52 797 402 -1 -1:</Data>
			</Layout2>
		</Layouts>
	</Instrumentation>
	<XILAPIEESPort>
		<ErrorConfigurationDocuments Version="1"/>
	</XILAPIEESPort>
</Root>